---
- name: Azure Inventory Configuration
  vars:
    ip_list: "{{ lookup ('file','ip.txt').splitlines() }}"
  gather_facts: false
  hosts: localhost
  tasks:
    - debug : 
        msg: "{{ip_list}}"
    - template:
        src: hosts.j2
        dest: host.conf
        mode: 0755
    
    
